version: '3'
# Just Comment 
networks:
  laravel:

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./laravel-app:/var/www/html/laravelapp
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./laravel-app:/var/www/html/laravelapp
    working_dir: /var/www/html/laravelapp
    depends_on:
      - php
    networks:
      - laravel
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks: 
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8888:80"
    volumes:
      - ./laravel-app:/var/www/html/laravelapp
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel